### ISSUE TITLE
Remindems are not exposed through API

### ISSUE THREAD

**Issue by pmallol** [instedd/remindem#17]
Found in version 1.6.2
 
1. Log in 
2. Navigate to Reminders
3. Create a reminder
4. Make a request through the API: http://remindem-stg.instedd.org/api/schedules.json

Obtained: 404 page and error in the console

Expected: a json exposing a list of the reminders in the account

**Comment by spalladino** [comment]
Endpoint is http://remindem-stg.instedd.org/api/reminders.json

**Comment by mmuller** [comment]
It is working fine on version 1.6.2
