### ISSUE TITLE
Migrate Ruby and Rails versions

### ISSUE THREAD

**Issue by nditada** [instedd/remindem#2]

**Comment by spalladino** [comment]
Update to Rails 4.1 and Ruby 2

**Comment by spalladino** [comment]
Update to Rails 3.2 and Ruby 2.0 is ready

**Comment by nditada** [comment]
can we close this one?

**Comment by spalladino** [comment]
If we agree that we're good on Rails 3.2 and Ruby 2.0, sure.

**Comment by nditada** [comment]
Good for now.
