### ISSUE TITLE
'New subscriber' as an event in Hub not executing any action 

### ISSUE THREAD

**Issue by pmallol** [instedd/remindem#20]
Found in version 1.6.2
(Hub version 1a700c0)

Preconditions:
User has an enabled reminder in Remindem and an external trigger set with Oauth in mBuilder.

1. Go to Hub and navigate to Tasks
2. Create a task
    * Add 'new subscriber' in Remindem as the event
    * Add 'trigger' an external trigger as the action
3. Make a POST to Remindem with Basic Auth to create a new subscriber through the API (e.g: http://remindem-stg.instedd.org/api/reminders/1/subscribers.json?phone_number=111111)

Obtained: the subscriber is added in the reminder but the external trigger isn't executed. Hub's log does not show any change after the event was reproduced. 
NOTE: this happens also when the action is from another connector.

Expected: the external trigger is executed successfully through hub.

**Comment by spalladino** [comment]
Fixed configuration issue in `hub.yml` in staging instance.

**Comment by mmuller** [comment]
Ok in version:
1.6.2 (Remidem)
1a700c0 (Hub)
