### ISSUE TITLE
Subscriber phone cannot be inserted into Pollit

### ISSUE THREAD

**Issue by mmuller** [instedd/remindem#27]
Found in version: 1.6.2
Pollit version 4b841128a9dac5d66b26b99f0f0de05a452b651d

Preconditions: 
There is Poll 'Foo' (Pollit)

Steps:
Go to create a Reminder
Press the button '+' to add a new message
Choose 'External Action'
Select Pollit connector 
Choose the Poll 'Foo'
Select the 'Respondents' option
Press the Select button

Obtained:
-The loading spinner is not hidden
-The properties are not shown

![screen shot 2015-03-13 at 1 27 51 pm](https://cloud.githubusercontent.com/assets/518152/6642628/cfd31a4a-c984-11e4-9482-f999cf5598ab.png)

![screen shot 2015-03-13 at 1 28 36 pm](https://cloud.githubusercontent.com/assets/518152/6642659/fcdb3734-c984-11e4-963b-34d17efeebad.png)

**Comment by spalladino** [comment]
@mmuller can we identify if this is a problem that happens only when connecting remindem to pollit, or it happens anytime a subscriber tries to be inserted in pollit?

**Comment by mmuller** [comment]
@spalladino I am testing it in Hub and I getting the same result. 
I moved this issue to Pollit: https://github.com/instedd/pollit/issues/25
