### ISSUE TITLE
External action step

### ISSUE THREAD

**Issue by nditada** [instedd/remindem#5]
- [x] transform the plus button to add messages to a dropdown. Keep the default to "add message". Add a new option with "external action"
- [x] display the hub action selector
- [x] show a dropdown next to each target parameter with internal fields, for now: subscriber phone_number, days_registered.
- [x] trigger hub action when the time for that step comes.

**Comment by vtiffenberg** [comment]
I am not considering open structs for this case. Other than that, it seems ready

**Comment by mmuller** [comment]
It is not working in version: 1.6.2

-Subscriber phone cannot be inserted into Google Spreadsheet. The following JS Error is thrown:
Uncaught TypeError: Cannot read property 'result' of null
eaFormToObject
MessageControls
validate_fields
confirm_changes
onclick

-When trying to save a Reminder that executes an External Trigger (mBuilder) throws Server Error

-When trying to save a Reminder that insert a subcriber into the Phone Book (Verboice) throws Server Error

**Comment by mmuller** [comment]
Further details for the Google Spreadsheet connector:
 -The loading spinner is not hidden and the following JS Error is thrown:
Uncaught ReferenceError: new_el is not defined
renderForm
(anonymous function)
e._performPromise
(anonymous function)
K.Callbacks.f
K.Callbacks.d.fireWith
r
K.support.ajax.K.ajaxTransport.send.r

**Comment by vtiffenberg** [comment]
Couldn't reproduce any of the cases: both ExternalTriggers and PhoneBook are saved fine. Spreadsheet was an issue for me because I got an error on Hub's side. 

I think this may be fixed as a side effect of #23 though. Please test again after next deploy and reopen if it still fails.

**Comment by mmuller** [comment]
Found on version 1.6.2

When trying to save a Reminder that insert a subscriber into the Phone Book (Verboice) throws Server Error

Steps:
Go to create a new Reminder
Select an External Action 
Choose the option to insert into Verboice Phonebook
Save the message
Save the Reminder

Obtained:
Server error is thrown

**Comment by mmuller** [comment]
Ok in version 1.6.2
